###服务启动端口号
server:
  port: 8010
###服务名称(服务注册到eureka名称)
spring:
  application:
    ####对应的git上项目应用名称，Eureka
    name:  sayHello
  cloud:
    config:
      ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
        ###config-server的服务别名
        service-id: config-server
        ###开启读取权限
        enabled: true


###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true



