###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
### 配置网关反向代理
zuul:
  routes:
    #定义服务转发规则，api-a这个名字可以随便起
    api-a:
      ### 以 /api-hello/路径访问转发到hello服务
      path: /api-hello/**
      serviceId: app-screw-hello
    api-b:
      ### 以 /api-order/路径访问转发到订单服务
      path: /api-order/**
      serviceId: app-screw-Order
